### ISSUE TITLE
nginx服务器配置

### ISSUE THREAD

**Issue by prlei** [r-nacos/r-nacos#42]
操作系统：AlmaLinux8
我尝试了开放10848端口，可以正常访问控制台
但是我放到nginx中，怎么配置都不行，提示：
<img width="710" alt="image" src="https://github.com/r-nacos/r-nacos/assets/3824622/21eeaa9b-c261-427f-ba50-9fc5231729e1">

// 这个看起来302失败 ？看下面的端口7890，是内部跳转么，我看服务器没有这个端口的信息。
//开放端口时，我看应该是302到了 http://127.0.0.1:18848/p/login...... 这个url，不知道是否有什么影响
<img width="571" alt="image" src="https://github.com/r-nacos/r-nacos/assets/3824622/2a9b36d3-80ed-4bb0-a7fc-705110f334ca">

----
我的nginx正常配置：
location /rnacos {
   proxy_pass         http://127.0.0.1:18848;
}
求指导。

**Comment by heqingpan** [comment]
这个应该是nginx配置的问题。
我晚上下班回去后，提供一个可用的配置出来。

**Comment by prlei** [comment]
非常感谢，辛苦······

**Comment by heqingpan** [comment]
@prlei 

1、 r-nacos 的302跳转需要把请求的Host传给r-nacos 服务。在 proxy_pass 前加上`proxy_set_header Host $proxy_host;` 使其能传递浏览器请求的 Host。
2、r-nacos的控制台使用绝对路径跳转，所以需要从根目录`location /`转发。
如果同一个端口号和现有服务的路径有冲突，可以使用二级域名（有可能需要调整DNS解析）。

按上面的逻辑 r-nacos 控制台的 nginx 配置如下：

```
server {
    listen       80;

    #  xxx.com 表示用户当前的域名，r-nacos.xxx.com表示对应的二级域名。
    server_name  r-nacos.xxx.com; 

    location / {
        proxy_set_header Host $proxy_host;
        proxy_pass  http://127.0.0.1:10848;
    }
}
```

-----

对rust的轻量级 ci/cd，这块目前我也不了解。

**Comment by prlei** [comment]
感谢回答，不过
1. 真不想用二级域名处理
2. jenkins也是根路径，但是日常配置成类似这样，就可以访问
location /jenkins {
    proxy_pass         http://127.0.0.1:8080;
}
====
就是说 要配置成  http://127.0.0.1/rnacos. 这种形式，目前是不支持是吧？

**Comment by heqingpan** [comment]
目前不支持这种二级目录转发方式。

收到你的这类需求，后面考虑把控制台前后端路径放到二级目录或者支持配置相对路径，以支持这类需求。
