### ISSUE TITLE
太牛了，我这儿刚想学学rust，你这人rnacos已经挫出来了。

### ISSUE THREAD

**Issue by limng06** [r-nacos/r-nacos#44]
太牛了，我这儿刚想学学rust，你这人rnacos已经挫出来了。
太牛了，我这儿刚想学学rust，你这人rnacos已经挫出来了。
太牛了
太牛了
太牛了
太牛
牛
牛
牛
牛

**Comment by heqingpan** [comment]
谢谢夸奖。

然后有点不好意思，这个issue先关闭了
