### ISSUE TITLE
控制台前后端路径放到二级目录,支持以二级目录把r-nacos转发到已有的域名上。

### ISSUE THREAD

**Issue by heqingpan** [r-nacos/r-nacos#46]
目前r-nacos的控制台使用绝对路径，依赖的路径是`/`，如果需要新建一个独立二级域名给它使用，不然会和已有的服务相互干扰。

方案：把控制台前后端的路径都放到`/rnacos/`下，支持以二级目录做转发。

关联需求 #42

**Comment by FlowerBirds** [comment]
建议放到/nacos/路径下，支持可以配置，方便通过nginx等代理访问

**Comment by heqingpan** [comment]
> 建议放到/nacos/路径下，支持可以配置，方便通过nginx等代理访问


这个就是为了方便nginx转发代理。

路径上是/rnacos/ 还是 /nacos/应该区别不大。
用/rnacos/主要是考虑支持和nacos共存、不冲突。

关于路径可配置，因为这个路径在前端可能是写死的，发布后就不好再配置。

**Comment by heqingpan** [comment]
【2024-03-30 记录】
初步完成把控制台前后端的路径都放到/rnacos/下功能开发，回归测试验证通过后再发布新版本。

**Comment by heqingpan** [comment]
最新的版本v0.5.2已支持此功能。

**Comment by heqingpan** [comment]
补充一个nginx转发配置

```
    location /rnacos {
        proxy_set_header Host $proxy_host;
        proxy_pass http://127.0.0.1:10848;
    }

```
