### ISSUE TITLE
nacos鉴权

### ISSUE THREAD

**Issue by Raxukl** [r-nacos/r-nacos#49]
是不是最新的版本还不支持鉴权操作，还有个就是有linux arm架构的包吗？

**Comment by heqingpan** [comment]
1.关于鉴权，目前r-nacos是通过mock支持鉴权接口请求接口。所以鉴权流程能走通，但实际r-nacos内部不校验。
    2.linux arm目前没有打包，可以先用docker运行，docker支持 arm。需求收到，后面的版本我再加下liunx arm包。

**Comment by Raxukl** [comment]
好的好的，我看了开发计划这个内部校验是等控制台完善之后再加吗？

**Comment by heqingpan** [comment]
是的，后续还是有计划支持的。

计划把鉴权信息和用户信息分开管理。鉴权计划可按应用维度管理。

再这之前控制台的接口与面向sdk的接口要独立管理。目前暴露的端口号已分开，但内部有部分接口还是共用。

另外就算加了鉴权，面向sdk的服务端口也不能暴露到外网，有风险。
个人判断只在内网使用的话，是否启用鉴权影响不是非常大。
所以把这块的优先级放低了一些。

**Comment by Raxukl** [comment]
收到

**Comment by Raxukl** [comment]
顺便再问一个小问题，linux启动的时候有参数控制停止、重新启动，还有以守护进程模式启动吗？目前我还是kill

**Comment by heqingpan** [comment]
你可以参考这个文档，以systemd方式托管运行。

https://r-nacos.github.io/docs/notes/deploy_example/linux_systemd_deploy/

**Comment by Raxukl** [comment]
这样通常会涉及到root权限吧，生产环境一般都是低权用户

**Comment by heqingpan** [comment]
上面的要样例支持普通用户的说明，支持普通用户被注释掉了。
开启对应注释即可。

**Comment by Raxukl** [comment]
我理解，但是一般给到的用户权限基本只有那么一个目录，其他的目录都要申请权限。所以有参数重启、启动、停止这些操作会不会更好些

**Comment by Raxukl** [comment]
我理解，但是一般给到的用户权限基本只有那么一个目录，其他的目录都要申请权限。所以有参数重启、启动、停止这些操作会不会更好些

**Comment by heqingpan** [comment]
重启、启动、停止服务这类操作和对应的托管启动方式有关。
使用systemd只是一种部署方式。

如果想要在不有sudo权限用户下部署，那可能要换其它部署方式，比如写个shell部署脚本。

关于linux托管部署方式有比较多，r-nacos暂时没有计划在服务层面支持这类功能。

如果有很多人有这类需求的话，可能也是用sidecar的方式支持。比如提供一可以管理部署过程的shell脚本。

**Comment by heqingpan** [comment]
重启、启动、停止服务这类操作和对应的托管启动方式有关。
使用systemd只是一种部署方式。

如果想要在不有sudo权限用户下部署，那可能要换其它部署方式，比如写个shell部署脚本。

关于linux托管部署方式有比较多，r-nacos暂时没有计划在服务层面支持这类功能。

如果有很多人有这类需求的话，可能也是用sidecar的方式支持。比如提供一可以管理部署过程的shell脚本。
