### ISSUE TITLE
只保留一个控制台

### ISSUE THREAD

**Issue by falcon-jin** [r-nacos/r-nacos#51]
8848那个控制台没有权限控制，是否可以考虑关掉8848的控制台 或者将10848的控制台合并到8848 只保留一个控制台

**Comment by heqingpan** [comment]
只保留一个的话，就只留10848。

如果合并到8848那么控制台就不能对外暴露，有风险。

之前也是有这个计划，会在合适的时机把8848的控制台关掉。

**Comment by PterX** [comment]
> 只保留一个的话，就只留10848。
> 
> 如果合并到8848那么控制台就不能对外暴露，有风险。
> 
> 之前也是有这个计划，会在合适的时机把8848的控制台关掉。

能不能给加上oidc header认证，这样子可以方便和单点网关进行集成

**Comment by heqingpan** [comment]
> > 只保留一个的话，就只留10848。
> > 如果合并到8848那么控制台就不能对外暴露，有风险。
> > 之前也是有这个计划，会在合适的时机把8848的控制台关掉。
> 
> 能不能给加上oidc header认证，这样子可以方便和单点网关进行集成

关于接入单点登录，这算是一个扩展功能。
功能上有支持接入单点登录的计划，不过排期上应该会在r-nacos整体功能完成之后，时间上会晚一些。

**Comment by heqingpan** [comment]
> 8848那个控制台没有权限控制，是否可以考虑关掉8848的控制台 或者将10848的控制台合并到8848 只保留一个控制台

最新的版本v0.5.2已支持只保留一个控制台此功能，默认只保留10848的控制台。
