### ISSUE TITLE
Open API兼容性问题和token生成问题

### ISSUE THREAD

**Issue by ljd1995** [r-nacos/r-nacos#52]
hello, 偶然发现一个nacos的rust实现，下载看了下，很轻巧，页面也很友好，正在研究能否替换内部项目的nacos,发现一些问题，还请作者看看

1. token生成问题
`http POST http://127.0.0.1:8848/nacos/v1/auth/login username=nacos password=nacos`

返回值：
![image](https://github.com/r-nacos/r-nacos/assets/17735771/47cc6fe1-68a8-4107-9e70-67f6a799d7fc)

token值为mock_token，不知道是否有意为之，还是还未实现到这步，看源码是写死的
![image](https://github.com/r-nacos/r-nacos/assets/17735771/a641ef70-3442-4ead-8a65-f4e0c3081ccf)

2. open api返回值兼容性
`http GET http://127.0.0.1:8848/nacos/v1/console/namespaces`

r-nacos 返回值
![image](https://github.com/r-nacos/r-nacos/assets/17735771/2621f518-0e69-4491-9b99-23405b523876)

nacos官方API返回值
![image](https://github.com/r-nacos/r-nacos/assets/17735771/985853a9-2603-4247-a9a0-6c8168c5cff5)

返回值data属性字段是对不上的，如namespaceShowName-->namespaceName，这就导致目前原有代码无法直接兼容r-nacos

不知道是否可做兼容

**Comment by heqingpan** [comment]
1. 第1点问题场景原由 可以参考之前的issue #49
2. 这个接口字段可以兼容，后续的版本加上。至于为什么之前没有兼容，因为它是面向控制台的接口，设计上不必考虑兼容。只承诺完全兼容面向sdk的接口。

**Comment by heqingpan** [comment]
1. 第1点问题场景原由 可以参考之前的issue #49
2. 这个接口字段可以兼容，后续的版本加上。至于为什么之前没有兼容，因为它是面向控制台的接口，设计上不必考虑兼容。只承诺完全兼容面向sdk的接口。
