### ISSUE TITLE
支持css/js 缓存提高页面加载效率

### ISSUE THREAD

**Issue by PterX** [r-nacos/r-nacos#53]
建议支持css/js 缓存支持，这两个的大小非常大，速度不理想的时候很慢

**Comment by heqingpan** [comment]
关于前端加载速度的优化，目前有个共建的前端开发正在处理，优化后应该能提升一些加载速度。

**Comment by heqingpan** [comment]
同时后面的版本的请求前端资源接口时，对js/css 响应增加启用缓存的header。

**Comment by PterX** [comment]
> 同时后面的版本的请求前端资源接口时，对js/css 响应增加启用缓存的header。

赞，非常感谢你们的工作

**Comment by heqingpan** [comment]
最新的版本v0.5.4已支持css/js 缓存提高页面加载效率

**Comment by PterX** [comment]
赞，已经能感受到了
