### ISSUE TITLE
集群部署，是必须用IP地址吗？我用域名测试一直不通过

### ISSUE THREAD

**Issue by GuoYingLong** [r-nacos/r-nacos#59]
集群部署，是必须用IP地址吗？我用域名测试一直不通过，使用docker swarm部署的，容器中可以互相通过域名ping通，集群一直连不上，提示DNS问题

**Comment by heqingpan** [comment]
要是必须用ip地址，理论上服务能连通就可以。

可以确认一下是否用的是grpc端口，网络是否被网关拦截。

docker的集群可以参考：  https://r-nacos.github.io/docs/notes/deploy_example/docker_cluster_deploy/

**Comment by GuoYingLong** [comment]
> 不是必须用ip地址，理论上服务能力就可以。
> 
> 可以确认一下是否用的是grpc端口，网络是否被网关拦截。
> 
> docker的集群可以参考： https://r-nacos.github.io/docs/notes/deploy_example/docker_cluster_deploy/

好的。我测试一下，非常感谢

**Comment by heqingpan** [comment]
@GuoYingLong 你好，你的问题已解决了吗？  如果已经解决，请关闭这个issue。
