### ISSUE TITLE
r-nacos 独立控制台不支持监听本地端口吗？

### ISSUE THREAD

**Issue by al0ne** [r-nacos/r-nacos#61]
如题：我在修改RNACOS_HTTP_CONSOLE_PORT 为 127.0.0.1:10848 时，发现不支持监听本地。
我想将r-nacos的独立控制台端口监听本地，然后通过Nginx套个自签名来访问。

**Comment by heqingpan** [comment]
端口号只是整数，前面不要加ip，具体可以参考配置说明。

默认就是监听本地的。

**Comment by al0ne** [comment]
RNACOS_HTTP_CONSOLE_PORT=10848，默认监听是0.0.0.0

```yaml
RNACOS_CONFIG_DB_DIR=nacos_db
RNACOS_CONSOLE_LOGIN_ONE_HOUR_LIMIT=5
RNACOS_ENABLE_NO_AUTH_CONSOLE=false
RNACOS_GRPC_PORT=0
RNACOS_HTTP_CONSOLE_PORT=10848
RNACOS_HTTP_PORT=0
RNACOS_RAFT_NODE_ADDR=127.0.0.1:9848
RNACOS_RAFT_NODE_ID=1
RUST_LOG=info
```

<img width="1238" alt="image" src="https://github.com/r-nacos/r-nacos/assets/13449320/1147de6d-8796-4afd-98d0-d892f69bb419">

**Comment by heqingpan** [comment]
你是想把ip 从0.0.0.0改成127.0.0.1是吗？

这个目前是不支持的，这个在什么场景下是必要的呢？

**Comment by al0ne** [comment]
了解，主要是想前面套个Nginx+自签名SSL 走https，这样nacos监听本地，通过Nginx开放出去。

**Comment by heqingpan** [comment]
那目前这个版本也是支持这个场景，你只要网关不开放10848端口出去就可以。

**Comment by al0ne** [comment]
好的
